### ISSUE TITLE
XML cannot be installed with pak

### ISSUE THREAD

**Issue by Robinlovelace** [r-lib/pak#430]
In https://github.com/r-lib/actions/issues/559 this issue was raised, with the solution being

> This should be now fixed with `pak-version: devel`.

However, that still does not seem to fix the issue. As described in that issue, I added `pak-version` as follows in the workflow yml file: https://github.com/ropensci/stplanr/commit/be98590ddad05add95c6899da20f0bc311658af0

```
        with:
          pak-version: devel
          extra-packages: any::pkgdown, local::.
          needs: website
```

This has also been attempted in other repos following that advice, e.g. https://github.com/statOmics/TargetDecoy/commit/db349bf9921af6b54fa3825e77f3c31e16209029

See here for the results:

https://github.com/ropensci/stplanr/actions/runs/3460324354/jobs/5776750388#step:5:6532

Many thanks for this great package, will make package installation much easier and already does for most package.
