### ISSUE TITLE
Could not find R package in `.` or its parent directories.

### ISSUE THREAD

**Issue by rjake** [r-lib/pak#576]
I am trying to adapt the [`pkgdown.yml`][1] workflow from `r-lib/actions` and it started failing on the step `setup-r-dependencies@v2`. I think it related to [this commit][2] that was released with version 0.7.1 on 12/11/23. I posted on [Stack Overflow][3] but didn't get any responses. I'm not sure if there is something in `pak` that can help, if the `r-lib/actions` workflow example needs to be updated, or if there is a better place to get help. Any advice is appreciated.

```yaml
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: self-hosted   # <---- self hosted
    container: ...

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    permissions:
      contents: write

    steps:
      - name: Install Required Packages
        run: apt-get update && apt-get install -y gdebi-core pandoc

      - uses: actions/checkout@v1
        
      - uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-r-dependencies@v2   # <--- fails here
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
```

```
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: ! pkgdepends resolution error for deps::..
  Caused by error: 
  ! Could not find R package in `.` or its parent directories.
  * any::pak=: ! pkgdepends resolution error for any::pak=.
  Caused by error: 
  ! missing value where TRUE/FALSE needed
  * local::.: ! pkgdepends resolution error for local::..
  Caused by error: 
  ! Could not find R package in `.` or its parent directories.
  ---
  Backtrace:
  1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
  7. | base::signalCondition(cond)
  8. global (function (e) …
  Execution halted
```

  [1]: https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml
  [2]: https://github.com/r-lib/pak/commit/4c3de70be30375916ce915774647dee30f8346c6#diff-fc9e58e398068fd9f6fb6fc51c882c20c3b7d9bc298f8045f6110a331eeb62d2
  [3]: https://stackoverflow.com/questions/77688296/github-action-failing-for-setup-r-dependencies

**Comment by gaborcsardi** [comment]
Please include a link to your workflow file, and to a failed build.

**Comment by rjake** [comment]
It's on our enterprise server so I don't have any links. Here is what we are running and the log for the `setup-r-dependencies` step. Also, I just barely understand actions. 

<details> 
<summary> yaml </summary> 

```yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  # because there is no "on merge" option, this workflow will run anytime a PR is closed or when manually triggered
  # if the PR is closed but not merged, the logic 'github.event.pull_request.merged == false' will be used during 
  # 'actions/checkout@v3' and the workflow will rebuild pages off of the main branch. This is an uneccessary build
  # but I can't find an alternative
  push:
    branches:
      - main
  workflow_dispatch: # run manually
    inputs:
      which-branch:
        description: "Which branch should be used to generate pages?"
        type: choice
        default: 'main'
        options:
        - main
        - this-pr

name: pkgdown

jobs:
  pkgdown:
    runs-on: self-hosted
    container: *****
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    permissions:
      contents: write

    steps:
      - name: Install Required Packages
        run: apt-get update && apt-get install -y gdebi-core pandoc

      - uses: actions/checkout@v1
        if: github.event.inputs.which-branch == 'main' # manually triggered + main selected
        with:
            ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Increase timeout
        shell: Rscript {0}
        run: options(timeout = max(300, getOption("timeout")))
        
      - uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        shell: Rscript {0}
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs # this is the location from pkgdown::build_site_github_pages() and not Settings > Pages

```

</details>

<details> 
<summary> log & error </summary> 

```bash
Run r-lib/actions/setup-r-dependencies@v[2](<server>/actions/runs/131606/job/220237#step:8:2)
  with:
    extra-packages: any::pkgdown, local::.
    needs: website
    cache: true
    cache-version: 1
    packages: deps::., any::sessioninfo
    pak-version: stable
    working-directory: .
    dependencies: "all"
    upgrade: FALSE
  env:
    GITHUB_PAT: ***
    R_KEEP_PKG_SOURCE: yes
    RENV_PATHS_ROOT: /runner/_work/_temp/renv
Run # Set site library path
  # Set site library path
  cat("::group::Set site library path\n")
  if (Sys.getenv("RENV_PROJECT") != "") {
    message("renv project detected, no need to set R_LIBS_SITE")
    cat(sprintf("R_LIB_FOR_PAK=%s\n", .libPaths()[1]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
    q("no")
  }
  lib <- Sys.getenv("R_LIBS_SITE")
  if (lib == "") {
    lib <- file.path(dirname(.Library), "site-library")
    cat(sprintf("R_LIBS_SITE=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
    cat(sprintf("R_LIB_FOR_PAK=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
    message("Setting R_LIBS_SITE to ", lib)
  } else {
    message("R_LIBS_SITE is already set to ", lib)
    cat(sprintf("R_LIB_FOR_PAK=%s\n", strsplit(lib, .Platform$path.sep)[[1]][[1]]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
  }
  cat("::endgroup::\n")
  shell: Rscript {0}
  env:
    GITHUB_PAT: ***
    R_KEEP_PKG_SOURCE: yes
    RENV_PATHS_ROOT: /runner/_work/_temp/renv
Set site library path
  renv project detected, no need to set R_LIBS_SITE
Run # Install pak
  # Install pak
  echo "::group::Install pak"
  if which sudo >/dev/null; then SUDO="sudo -E --preserve-env=PATH env"; else SUDO=""; fi
  $SUDO R -q -e 'dir.create(Sys.getenv("R_LIB_FOR_PAK"), recursive = TRUE, showWarnings = FALSE)'
  $SUDO R -q -e 'install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/", lib = Sys.getenv("R_LIB_FOR_PAK"))'
  echo "::endgroup::"
    upgrade = (FALSE),
    dependencies = c(needs, ("all"))
  )
  cat("::endgroup::\n")
  cat("::group::Show Lockfile\n")
  writeLines(readLines(".github/pkg.lock"))
  cat("::endgroup::\n")
  shell: Rscript {0}
  env:
    GITHUB_PAT: ***
    R_KEEP_PKG_SOURCE: yes
    RENV_PATHS_ROOT: /runner/_work/_temp/renv
    R_LIB_FOR_PAK: /__w/rocqi/rocqi/renv/library/R-4.2/x86_64-pc-linux-gnu
Dependency resolution
  Warning message:
  package ‘pak’ was built under R version 4.2.[3](<server>/actions/runs/131606/job/220237#step:8:3) 
  ℹ Creating lockfile '.github/pkg.lock'
  
  ✔ Updated metadata database: [4](<server>/actions/runs/131606/job/220237#step:8:4).43 MB in 9 files.
  
  ℹ Creating lockfile '.github/pkg.lock'
  ℹ Updating metadata database
  ✔ Updating metadata database ... done
  
  ℹ Creating lockfile '.github/pkg.lock'
  ✖ Creating lockfile '.github/pkg.lock' [11.2s]
  
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: ! pkgdepends resolution error for deps::..
  Caused by error: 
  ! Could not find R package in `.` or its parent directories.
  * local::.: ! pkgdepends resolution error for local::..
  Caused by error: 
  ! Could not find R package in `.` or its parent directories.
  ---
  Backtrace:
  1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  [5](<server>/actions/runs/131606/job/220237#step:8:5). pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  [6](<server>/actions/runs/131606/job/220237#step:8:6). base::throw(new_error("Could not solve package dependencies:\n", msg, …
  [7](<server>/actions/runs/131606/job/220237#step:8:7). | base::signalCondition(cond)
  [8](<server>/actions/runs/131606/job/220237#step:8:8). global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

</details>
